CREATE TABLE IF NOT EXISTS DF_WECHATORDERS
(
    ID                BIGINT NOT NULL AUTO_INCREMENT,
    OUT_TRADE_NO      VARCHAR(64),
    NONCE_STR         VARCHAR(64),
    ORDERSIGN         VARCHAR(256),
    TOTAL_FEE         DOUBLE(10,2),
    TRADE_TYPE        VARCHAR(32),
    PREPAY_ID         VARCHAR(256),
    CODE_URL          VARCHAR(256),
    CASH_FEE          DOUBLE(10,2),
    FEE_TYPE          VARCHAR(32),
    BANK_TYPE         VARCHAR(32),
    OPENID            VARCHAR(256),
    TRANSACTION_ID    VARCHAR(256),
    TIME_END          VARCHAR(32),
    CREATE_AT         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    REGION            VARCHAR(32),
    USERNAME          VARCHAR(32),
    NAMESPACE         VARCHAR(64),
    STATUS            VARCHAR(32),
    PRIMARY KEY (ID)
) DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS DF_ITEM_STAT
(
   STAT_KEY     VARCHAR(255) NOT NULL COMMENT '3*255 = 765 < 767',
   STAT_VALUE   INT NOT NULL,
   PRIMARY KEY (STAT_KEY)
) DEFAULT CHARSET=UTF8;
